test:
    path:     test
    defaults: { _controller: AppBundle:Test:index }


test1:
    path:     test1
    defaults: { _controller: AppBundle:Test:index1 }




test2:
    path:     test2
    defaults: { _controller: AppBundle:Test:index2 }
