index:
    path:     test
    defaults: { _controller: AppBundle:Test:index }


test1:
    path:     test1
    defaults: { _controller: AppBundle:Test:index }




test2:
    path:     test_2
    defaults: { _controller: AppBundle:Test:index }
