AppBundle\Entity\Dir:
    type: entity
    table: dir
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
          type: nested
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        lvl:
          type: integer
          gedmo:
            - treeLevel
        name:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        title:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        autoPath:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: auto_path
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        sortOrder:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: sort_order
    manyToOne:
        cover:
            targetEntity: Element
            inversedBy: null
            joinColumn:
                name: element_id_cover
                referencedColumnName: id

    manyToMany:
        group:
            targetEntity: Group
            cascade: {  }
            fetch: LAZY
            mappedBy: dir
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
