AppBundle\Entity\Product:
    type: entity
    repositoryClass: AppBundle\Repository\ProductRepository
    table: product
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: decimal
            scale : 2
    manyToOne:
            category:
                targetEntity: Category
                inversedBy: products
                joinColumn:
                    name: category_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }
